#!/usr/bin/env python3
"""Generate the LinguaPop app mark from one geometry spec.

The mark is the kanji 言 ("word") drawn as pure geometry: a short top stroke,
three horizontal bars, and an open box. Set in ink and paper it reads two ways
at once — as the character, and as columns of newsprint over a headline box —
which is exactly what the app is.

One spec, four outputs:
  * assets/icon/linguapop.svg                     — the human-editable source
  * android .../drawable/ic_launcher_foreground.xml — adaptive icon foreground
    (a VectorDrawable, so it also serves as the Android 13 monochrome layer)
  * android .../mipmap-*/ic_launcher.png          — legacy raster icons, API < 26
  * web/icons + favicon are left alone (the web build isn't shipped)

There's no image library or SVG rasteriser on this machine, so the PNGs are
rendered here with analytic per-pixel coverage (every shape is an axis-aligned
rectangle, so coverage is just an area overlap) and written through a minimal
PNG encoder. Corners are the only curved part and get supersampled.

Run:  python3 tool/make_icon.py
"""

import os
import struct
import zlib
from array import array

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
RES = os.path.join(ROOT, "android", "app", "src", "main", "res")

# ── palette ────────────────────────────────────────────────────────────────
INK = (0x14, 0x16, 0x1A)      # sumi — the icon ground
PAPER = (0xF4, 0xEF, 0xE3)    # newsprint — the strokes
SEAL = (0xD9, 0x4F, 0x4F)     # vermilion — the box, like a hanko

# ── the mark, in its own 0..1 box ──────────────────────────────────────────
# 言 = 亠 (top stroke) + 三 (three strokes) + 口 (box).
TOP = (0.345, 0.020, 0.655, 0.115)
BARS = [
    (0.090, 0.215, 0.910, 0.310),
    (0.090, 0.395, 0.910, 0.490),
    (0.090, 0.575, 0.910, 0.670),
]
MOUTH = (0.185, 0.715, 0.815, 1.000)
MOUTH_STROKE = 0.070

CORNER_RADIUS = 0.2237  # of the icon side — Android's legacy squircle-ish


def mouth_bars(box, t):
    """The open box 口, as four rectangles."""
    x0, y0, x1, y1 = box
    return [
        (x0, y0, x1, y0 + t),           # top
        (x0, y1 - t, x1, y1),           # bottom
        (x0, y0, x0 + t, y1),           # left
        (x1 - t, y0, x1, y1),           # right
    ]


def mark_shapes():
    """(rect, color) pairs in the mark's own unit box."""
    out = [(TOP, PAPER)]
    out += [(b, PAPER) for b in BARS]
    out += [(r, SEAL) for r in mouth_bars(MOUTH, MOUTH_STROKE)]
    return out


# ── SVG ────────────────────────────────────────────────────────────────────

def write_svg(path, side=512, mark_scale=0.62):
    """Full-bleed icon: rounded ink ground with the mark centred on it."""
    m = side * mark_scale
    ox = (side - m) / 2
    oy = (side - m) / 2
    r = side * CORNER_RADIUS

    def rect(rc, color):
        x0, y0, x1, y1 = rc
        return (
            f'  <rect x="{ox + x0 * m:.2f}" y="{oy + y0 * m:.2f}" '
            f'width="{(x1 - x0) * m:.2f}" height="{(y1 - y0) * m:.2f}" '
            f'fill="#{color[0]:02X}{color[1]:02X}{color[2]:02X}"/>'
        )

    body = "\n".join(rect(rc, c) for rc, c in mark_shapes())
    svg = f'''<svg xmlns="http://www.w3.org/2000/svg" width="{side}" height="{side}" viewBox="0 0 {side} {side}">
  <title>LinguaPop</title>
  <rect width="{side}" height="{side}" rx="{r:.2f}" ry="{r:.2f}" fill="#{INK[0]:02X}{INK[1]:02X}{INK[2]:02X}"/>
{body}
</svg>
'''
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(svg)
    return path


# ── Android adaptive icon (VectorDrawable) ─────────────────────────────────

def write_vector_foreground(path, viewport=108.0, mark_size=54.0):
    """Mark only, centred in the 108dp viewport, inside the 66dp safe zone."""
    ox = (viewport - mark_size) / 2
    oy = (viewport - mark_size) / 2

    def path_data(rc):
        x0, y0, x1, y1 = rc
        ax, ay = ox + x0 * mark_size, oy + y0 * mark_size
        bx, by = ox + x1 * mark_size, oy + y1 * mark_size
        return (f"M{ax:.3f},{ay:.3f} L{bx:.3f},{ay:.3f} "
                f"L{bx:.3f},{by:.3f} L{ax:.3f},{by:.3f} Z")

    paths = "\n".join(
        f'  <path android:fillColor="#{c[0]:02X}{c[1]:02X}{c[2]:02X}" '
        f'android:pathData="{path_data(rc)}"/>'
        for rc, c in mark_shapes()
    )
    xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/make_icon.py — edit the spec there, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{viewport:.0f}dp"
    android:height="{viewport:.0f}dp"
    android:viewportWidth="{viewport:.0f}"
    android:viewportHeight="{viewport:.0f}">
{paths}
</vector>
'''
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(xml)
    return path


def write_monochrome(path, viewport=108.0, mark_size=54.0):
    """Themed-icon layer: the same mark, single colour, tinted by the system."""
    ox = (viewport - mark_size) / 2
    oy = (viewport - mark_size) / 2

    def path_data(rc):
        x0, y0, x1, y1 = rc
        ax, ay = ox + x0 * mark_size, oy + y0 * mark_size
        bx, by = ox + x1 * mark_size, oy + y1 * mark_size
        return (f"M{ax:.3f},{ay:.3f} L{bx:.3f},{ay:.3f} "
                f"L{bx:.3f},{by:.3f} L{ax:.3f},{by:.3f} Z")

    paths = "\n".join(
        f'  <path android:fillColor="#FFFFFF" android:pathData="{path_data(rc)}"/>'
        for rc, _ in mark_shapes()
    )
    xml = f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by tool/make_icon.py — edit the spec there, not this file. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="{viewport:.0f}dp"
    android:height="{viewport:.0f}dp"
    android:viewportWidth="{viewport:.0f}"
    android:viewportHeight="{viewport:.0f}">
{paths}
</vector>
'''
    with open(path, "w") as f:
        f.write(xml)
    return path


# ── minimal raster renderer + PNG encoder ──────────────────────────────────

class Canvas:
    def __init__(self, w, h):
        self.w, self.h = w, h
        n = w * h
        self.r = array("f", [0.0]) * n
        self.g = array("f", [0.0]) * n
        self.b = array("f", [0.0]) * n
        self.a = array("f", [0.0]) * n

    def _blend(self, i, color, cov):
        if cov <= 0:
            return
        if cov > 1:
            cov = 1.0
        inv = 1.0 - cov
        self.r[i] = color[0] * cov + self.r[i] * inv
        self.g[i] = color[1] * cov + self.g[i] * inv
        self.b[i] = color[2] * cov + self.b[i] * inv
        self.a[i] = 255.0 * cov + self.a[i] * inv

    def fill_rect(self, x0, y0, x1, y1, color):
        """Analytic coverage — every shape in the mark is axis-aligned."""
        px0, px1 = max(0, int(x0)), min(self.w, int(x1) + 1)
        py0, py1 = max(0, int(y0)), min(self.h, int(y1) + 1)
        for y in range(py0, py1):
            oy = min(y1, y + 1) - max(y0, y)
            if oy <= 0:
                continue
            row = y * self.w
            for x in range(px0, px1):
                ox = min(x1, x + 1) - max(x0, x)
                if ox <= 0:
                    continue
                self._blend(row + x, color, ox * oy)

    def fill_round_rect(self, x0, y0, x1, y1, radius, color, samples=4):
        """Straight edges analytically; the four corners supersampled."""
        self.fill_rect(x0, y0 + radius, x1, y1 - radius, color)
        self.fill_rect(x0 + radius, y0, x1 - radius, y0 + radius, color)
        self.fill_rect(x0 + radius, y1 - radius, x1 - radius, y1, color)
        corners = [
            (x0 + radius, y0 + radius, int(x0), int(y0 + radius) + 1,
             int(x0), int(y0 + radius) + 1),
        ]
        del corners
        for cx, cy, bx0, by0 in (
            (x0 + radius, y0 + radius, x0, y0),
            (x1 - radius, y0 + radius, x1 - radius, y0),
            (x0 + radius, y1 - radius, x0, y1 - radius),
            (x1 - radius, y1 - radius, x1 - radius, y1 - radius),
        ):
            for y in range(max(0, int(by0)), min(self.h, int(by0 + radius) + 1)):
                row = y * self.w
                for x in range(max(0, int(bx0)),
                               min(self.w, int(bx0 + radius) + 1)):
                    hits = 0
                    for sy in range(samples):
                        py = y + (sy + 0.5) / samples
                        for sx in range(samples):
                            px = x + (sx + 0.5) / samples
                            dx, dy = px - cx, py - cy
                            if dx * dx + dy * dy <= radius * radius:
                                hits += 1
                    if hits:
                        self._blend(row + x, color, hits / (samples * samples))

    def to_png_bytes(self):
        raw = bytearray()
        for y in range(self.h):
            raw.append(0)  # filter: none
            row = y * self.w
            for x in range(self.w):
                i = row + x
                raw.append(int(self.r[i] + 0.5))
                raw.append(int(self.g[i] + 0.5))
                raw.append(int(self.b[i] + 0.5))
                raw.append(int(self.a[i] + 0.5))
        return png_wrap(self.w, self.h, bytes(raw))


def png_wrap(w, h, raw):
    def chunk(tag, data):
        c = struct.pack(">I", len(data)) + tag + data
        return c + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF)

    header = struct.pack(">IIBBBBB", w, h, 8, 6, 0, 0, 0)  # 8-bit RGBA
    return (b"\x89PNG\r\n\x1a\n"
            + chunk(b"IHDR", header)
            + chunk(b"IDAT", zlib.compress(raw, 9))
            + chunk(b"IEND", b""))


def render_legacy(side, mark_scale=0.62):
    c = Canvas(side, side)
    c.fill_round_rect(0, 0, side, side, side * CORNER_RADIUS, INK)
    m = side * mark_scale
    ox = oy = (side - m) / 2
    for (x0, y0, x1, y1), color in mark_shapes():
        c.fill_rect(ox + x0 * m, oy + y0 * m, ox + x1 * m, oy + y1 * m, color)
    return c


LEGACY_SIZES = {
    "mipmap-mdpi": 48,
    "mipmap-hdpi": 72,
    "mipmap-xhdpi": 96,
    "mipmap-xxhdpi": 144,
    "mipmap-xxxhdpi": 192,
}


def main():
    written = []
    written.append(write_svg(os.path.join(ROOT, "assets", "icon",
                                          "linguapop.svg")))
    written.append(write_vector_foreground(
        os.path.join(RES, "drawable", "ic_launcher_foreground.xml")))
    written.append(write_monochrome(
        os.path.join(RES, "drawable", "ic_launcher_monochrome.xml")))

    for folder, size in LEGACY_SIZES.items():
        out = os.path.join(RES, folder, "ic_launcher.png")
        os.makedirs(os.path.dirname(out), exist_ok=True)
        with open(out, "wb") as f:
            f.write(render_legacy(size).to_png_bytes())
        written.append(f"{out} ({size}px)")

    # A big one for the store listing / README.
    out = os.path.join(ROOT, "assets", "icon", "linguapop-512.png")
    with open(out, "wb") as f:
        f.write(render_legacy(512).to_png_bytes())
    written.append(out)

    for w in written:
        print("wrote", os.path.relpath(w, ROOT) if os.path.isabs(
            w.split(" (")[0]) else w)


if __name__ == "__main__":
    main()
